version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data2:/data/db"
    environment:
      - DB_DATABASE= dashboard
      - DB_HOST= db
      - DB_PORT= 27017
  api:
    build: api
    image: hygieia-api
    depends_on:
      - db
    ports:
      - "8080:8080"

  ui:
    build: UI
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"

  appdynamics-collector:
    build: collectors/performance/appdynamics
    image: hygieia-appdynamics-collector
    depends_on:
      - db
    environment:
      - APD_CRON=0 0/1 * * * *
      - APD_URLS=https://erie-prod.saas.appdynamics.com
      - APD_USERNAME=scriptHygieiaTst@erie-prod
      - APD_PASSWORD=apiReader
      - APD_DASHBOARD_URL=https://erie-prod.saas.appdynamics.com/controller/#/location=APPS_ALL_DASHBOARD&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&dashboardMode=force

  udeploy-collector:
    build: collectors/deploy/udeploy
    image: hygieia-udeploy-collector
    depends_on:
      - db
    environment:
      - UCD_CRON= 0 0/1 * * * *
      - UCD_SERVER= https://prducd01:8443
      - UCD_TOKEN= 6b9f6628-3a01-4d89-94ce-eff58aca318e

  mendix-collector:
    build: collectors/mendix
    image: hygieia-mendix-collector
    depends_on:
      - db
    environment:
      - MENDIX_APPNAME=eriesecurebusiness100
      - MENDIX_USERNAME=pavan.nellore@valuemomentum.biz
      - MENDIX_APIKEY=19ae4922-55c3-4750-ba6f-57ba7b69dc56

  subversion-collector:
    build: collectors/scm/subversion
    image: hygieia-subversion-scm-collector
    depends_on:
      - db
    environment:
      - SUBVERSION_HOST=https://prdwinbld02.erieinsurance.com
      - SUBVERSION_USERNAME=xa662
      - SUBVERSION_PASSWORD=Jana123

volumes:
  db-data2:
  certs2:

